baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Data'
pageRef = '/data'
weight = 30

[[menus.main]]
name = 'CV'
pageRef = '/cv'
weight = 40

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
